---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Create a new EC2 key
    ec2_key:
      name: idopkeys
      region: us-east-1
#     state: absent
    register: ec2_key_result

  - debug:
      msg: "{{ ec2_key_result }}"

  - name: Save private key
    copy: content="{{ ec2_key_result.key.private_key }}" dest="./keys/idopkeys.pem" mode=0600
    when: ec2_key_result.changed
